import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Herosection from "@/components/Herosection";
import Secoundsection from "@/components/Secoundsection";
import Thiredsection from "@/components/Thiredsection";
import Fourthsection from "@/components/Fourthsection";
import Upcomingwebners from "@/components/Upcomingwebners";
import Animatedend from '@/components/Animatedend'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className='dark w-[99.3vw] overflow-x-hidden'>
      <body className={inter.className}>
        <div className="w-full h-fit relative ">
        <Navbar/>
        
        <Herosection/>
        <Secoundsection/>
        <Thiredsection/>
        <Fourthsection/>
        <Animatedend/>
        </div>
        {children}
      </body>
    </html>
  );
}
